### PR TITLE
stmt fetching error as user exception

### LINKED ISSUE #107: PDOException:SQLSTATE[IMSSP]: Field 30 returned no data
related to https://github.com/keboola/db-extractor-mssql/issues/46
should it be a user error?
`
failed: (2) [2019-02-05 03:18:30] CRITICAL: PDOException:SQLSTATE[IMSSP]: Field 30 returned no data. {"errFile":"/code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php","errLine":289,"errCode":"IMSSP","errTrace":"#0 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(289): PDOStatement->fetch(2)\n#1 /code/src/Keboola/DbExtractor/Extractor/MSSQL.php(255): Keboola\\DbExtractor\\Extractor\\Extractor->writeToCsv(Object(PDOStatement), Object(Keboola\\Csv\\CsvFile), true)\n#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(170): Keboola\\DbExtractor\\Extractor\\MSSQL->export(Array)\n#3 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()\n#4 /code/src/run.php(55): Keboola\\DbExtractor\\Application->run()\n#5 {main}","errPrevious":"PDOException"} []
`

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #107

### CODE REVIEW

File: src/Keboola/DbExtractor/Extractor/MSSQL.php [hunk 1]
```diff
@@ -267,6 +267,8 @@ public function export(array $table): array
                 }
             } catch (CsvException $e) {
                 throw new ApplicationException("Write to CSV failed: " . $e->getMessage(), 0, $e);
+            } catch (\PDOException $PDOException) {
```
Comment (tomasfejfar) [inline src/Keboola/DbExtractor/Extractor/MSSQL.php]: mismatch with the $e you're using in exception!!!!

File: tests/Keboola/DbExtractor/MSSQLTest.php [hunk 2]
```diff
@@ -1581,4 +1581,18 @@ public function testStripNulls(): void
...
+    {
+        $config = $this->getConfig(self::DRIVER);
+        unset($config['parameters']['tables'][1]);
+        unset($config['parameters']['tables'][2]);
+        unset($config['parameters']['tables'][3]);
+        unset($config['parameters']['tables'][0]['table']);
+        $config['parameters']['tables'][0]['query'] = "SELECT usergender INTO #temptable FROM sales WHERE usergender LIKE 'undefined';  SELECT * FRoM sales WHERE usergender IN (SELECT * FROM #temptable);";
+        $config['parameters']['tables'][0]['outputTable'] = 'in.c-main.multipleselect_test';
+
+        $this->setExpectedException(UserException::class);
```
Comment (tomasfejfar) [inline tests/Keboola/DbExtractor/MSSQLTest.php]: Always expect also the message to make sure it's thrown correctly. This issue would easily be prevented if you did that 😉 

How it could actually throw UserException if the throwing should throw notice exceptino because of missing `$e`? 
image

File: src/Keboola/DbExtractor/Extractor/MSSQL.php (hunk 1 above)
Comment (pivnicek) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: omg, and since $e is defined above in scope it was not caught by stan.  Thank you for catching this!

**Comment by pivnicek** [comment]
@tomasfejfar so sorry for this slipping under my radar, thanks a lot for catching that dumb mistake.

I believe it's all good now.

File: tests/Keboola/DbExtractor/MSSQLTest.php [hunk 3]
```diff
@@ -1592,7 +1592,10 @@ public function testMultipleSelectStatements(): void
         $config['parameters']['tables'][0]['query'] = "SELECT usergender INTO #temptable FROM sales WHERE usergender LIKE 'undefined';  SELECT * FRoM sales WHERE usergender IN (SELECT * FROM #temptable);";
         $config['parameters']['tables'][0]['outputTable'] = 'in.c-main.multipleselect_test';
 
-        $this->setExpectedException(UserException::class);
+        $this->setExpectedException(
```
Comment (tomasfejfar) [inline tests/Keboola/DbExtractor/MSSQLTest.php]: this was removed in latest PhpUnit use expectException() + expectExceptionMessage() instead.

Comment (pivnicek) [reply tests/Keboola/DbExtractor/MSSQLTest.php]: ok

Comment (pivnicek) [reply tests/Keboola/DbExtractor/MSSQLTest.php]: @tomasfejfar should I update phpunit then?  right now it's not on 7 yet.  how about we make that a different PR?

Comment (tomasfejfar) [reply tests/Keboola/DbExtractor/MSSQLTest.php]: No need to update. It's just current best practice. Update shall be part of the db-ex sync effort later...

Comment (tomasfejfar) [reply tests/Keboola/DbExtractor/MSSQLTest.php]: My rule of thumb is that is should not be used in newly written code. It's just fine to be kept in existing code.

Comment (tomasfejfar) [reply tests/Keboola/DbExtractor/MSSQLTest.php]: If you don't like it, it's fine with me.

Comment (pivnicek) [reply tests/Keboola/DbExtractor/MSSQLTest.php]: oh, don't get me wrong, I wanted to do it, but `expectException() + expectExceptionMessage() ` are not yet defined in the version of phpunit this is using :-)
