### PR TITLE
Fix datetime incremental fetching

### LINKED ISSUE #79: Fix unstable incremental fetching by timestamp test
ref: https://keboola.slack.com/archives/C035LGNK5/p1540994105019200

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #79 and #84

### CODE REVIEW

File: src/Keboola/DbExtractor/Extractor/MSSQL.php [hunk 1]
```diff
@@ -722,9 +724,9 @@ private function getIncrementalQueryAddon(): ?string
                     );
                 } else if ($this->incrementalFetching['type'] === self::TYPE_TIMESTAMP) {
                     $incrementalAddon = sprintf(
-                        " WHERE CONVERT(DATETIME2, %s, 121) > CONVERT(DATETIME2, '%s', 121)",
+                        " WHERE %s > %s",
```
Comment (tomasfejfar) [inline src/Keboola/DbExtractor/Extractor/MSSQL.php]: Could you elaborate why this now works when it did not before?

File: src/Keboola/DbExtractor/Extractor/MSSQL.php [hunk 2]
```diff
@@ -722,9 +724,9 @@ private function getIncrementalQueryAddon(): ?string
...
                         $this->quote($this->incrementalFetching['column']),
-                        $this->state['lastFetchedRow']
+                        $this->db->quote($this->state['lastFetchedRow'])
```
Comment (tomasfejfar) [inline src/Keboola/DbExtractor/Extractor/MSSQL.php]: The quoting is getting pretty rediculous `$this->quote` vs `$this->db->quote` each doing something different :D

File: tests/Keboola/DbExtractor/IncrementalFetchingTest.php [hunk 3]
```diff
@@ -30,6 +31,16 @@ public function testIncrementalFetchingByTimestamp(): void
         sleep(2);
         // the next fetch should be empty
         $emptyResult = ($this->createApplication($config, $result['state']))->run();
+        if ($emptyResult['imported']['rows']) {
+            $res = $this->pdo->query("SELECT * FROM [auto Increment Timestamp] ORDER BY [timestamp]");
```
Comment (tomasfejfar) [inline tests/Keboola/DbExtractor/IncrementalFetchingTest.php]: Why? And the message should be gone!

Comment (tomasfejfar) [reply tests/Keboola/DbExtractor/IncrementalFetchingTest.php]: Why is it doing the query?

File: src/Keboola/DbExtractor/Extractor/MSSQL.php (hunk 2 above)
Comment (pivnicek) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: Yeah, I think that in 10 the `$this->quote` is being renamed to `quoteIdentifier` which should help disambiguate it.

File: src/Keboola/DbExtractor/Extractor/MSSQL.php (hunk 1 above)
Comment (tomasfejfar) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: That said it's now still prone to the millisecond issue, isn't it? It's the same issue as I've just encountered when reviewing https://github.com/keboola/ex-ftp/pull/1, albeit harder to fix here.

Comment (pivnicek) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: No, because we're getting the correct value for state now https://github.com/keboola/db-extractor-mssql/pull/85/files#diff-b62d461d3edce69713b325b36fea667dR81
That was the real fix.
