### PR TITLE
retry gettables

### LINKED ISSUE #109: TCP Provider: Error code 0x2746
```
[2019-03-18 20:00:42] CRITICAL: PDOException:SQLSTATE[08S01]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 

{
    "errFile": "/code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php",
    "errLine": 289,
    "errCode": "08S01",
    "errTrace": "#0 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(289): PDOStatement->fetch(2)\n#1 /code/src/Keboola/DbExtractor/Extractor/MSSQL.php(255): Keboola\\DbExtractor\\Extractor\\Extractor->writeToCsv(Object(PDOStatement), Object(Keboola\\Csv\\CsvFile), true)\n#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(166): Keboola\\DbExtractor\\Extractor\\MSSQL->export(Array)\n#3 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()\n#4 /code/src/run.php(55): Keboola\\DbExtractor\\Application->run()\n#5 {main}",
    "errPrevious": ""
}

#0 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(289): PDOStatement->fetch(2)
#1 /code/src/Keboola/DbExtractor/Extractor/MSSQL.php(255): Keboola\\DbExtractor\\Extractor\\Extractor->writeToCsv(Object(PDOStatement), Object(Keboola\\Csv\\CsvFile), true)
#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(166): Keboola\\DbExtractor\\Extractor\\MSSQL->export(Array)
#3 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()
#4 /code/src/run.php(55): Keboola\\DbExtractor\\Application->run()
#5 {main}

```

maybe a retry will suffice?

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #109

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -1,4 +1,4 @@
-FROM php:7.2-cli
+FROM php:7.2-cli-stretch
```
Comment (tomasfejfar) [inline Dockerfile]: I tried to just switch the version from 9 to 10 below, but that does not work :( This will still need to be solved, but for now it seems good enough.

File: src/Keboola/DbExtractor/Extractor/MSSQL.php [hunk 2]
```diff
@@ -323,7 +324,16 @@ function ($row) {
 
     public function getTables(?array $tables = null): array
     {
-        return $this->metadataProvider->getTables($tables);
+        $proxy = new RetryProxy($this->logger);
+        return $proxy->call(function () use ($tables): array {
+            try {
+                return $this->metadataProvider->getTables($tables);
+            } catch (\Throwable $exception) {
+                $this->db = $this->createConnection($this->getDbParameters());
```
Comment (tomasfejfar) [inline src/Keboola/DbExtractor/Extractor/MSSQL.php]: What about doing $this->isAlive() and disconnect+reconnect conditionally - the original db object may not get garbage collected and the db connection may still be active which could have some implications... also getTables() may get called on any number of places, so it may disconnect the existing query or something...

File: src/Keboola/DbExtractor/Extractor/MSSQL.php [hunk 3]
```diff
@@ -4,10 +4,11 @@
 
 namespace Keboola\DbExtractor\Extractor;
 
+use Symfony\Component\Process\Process;
```
Comment (tomasfejfar) [inline src/Keboola/DbExtractor/Extractor/MSSQL.php]: Where does this come from?

Comment (pivnicek) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: old line 10 :-).  just re-ordered alphabetically

File: src/Keboola/DbExtractor/Extractor/MSSQL.php (hunk 2 above)
Comment (pivnicek) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: ok.  please see latest commit

**Comment by pivnicek** [comment]
Thanks @tomasfejfar , I've added the `isAlive()` condition.  Good idea.

File: src/Keboola/DbExtractor/Extractor/MSSQL.php (hunk 3 above)
Comment (tomasfejfar) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: Oh sorry, my fucked up reading again

File: src/Keboola/DbExtractor/Extractor/MSSQL.php (hunk 2 above)
Comment (tomasfejfar) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: Oh, the isAlive works differently from what I though. It throws `DeadConnectionException`... so it must be try/catch and reconnect in catch...

Comment (pivnicek) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: nice catch!  sorry, I should have checked that first...
