### PR TITLE
Fix incr fetching

### LINKED ISSUE #100: BCP export finishes but then fails
Source: https://keboola.zendesk.com/agent/tickets/9663

`The BCP export failed: Return value of Keboola\DbExtractor\Extractor\MSSQL::getLastFetchedDatetimeValue() must be of the type string, null returned. Attempting export using pdo_sqlsrv.`

BCP successfully export items, but then fails on error above and continue with second export through PDO.

### PR DESCRIPTION
**Pull request by pivnicek**
fix #100

### CODE REVIEW

File: src/Keboola/DbExtractor/Extractor/MSSQL.php [hunk 1]
```diff
@@ -781,23 +781,11 @@ private function getIncrementalQueryAddon(): ?string
...
-                        " WHERE %s >= %s",
-                        $this->quote($this->incrementalFetching['column']),
-                        $this->db->quote($this->state['lastFetchedRow'])
-                    );
-                } else {
-                    throw new ApplicationException(
-                        sprintf('Unknown incremental fetching column type %s', $this->incrementalFetching['type'])
-                    );
-                }
+                $incrementalAddon = sprintf(
```
Comment (tomasfejfar) [inline src/Keboola/DbExtractor/Extractor/MSSQL.php]: isn't there a difference between `WHERE column >= 7` and `WHERE column >= '7'`? Something like "column decimal cannot be converted to string" or something...

File: tests/Keboola/DbExtractor/ApplicationTest.php [hunk 2]
```diff
@@ -427,7 +427,7 @@ public function testIncrementalFetchingWithNullSmalldatetimeValues(): void
         $process->mustRun();
 
         $this->assertNotContains(
-            "The BCP export failed: Return value of Keboola\DbExtractor\Extractor\MSSQL::getLastFetchedDatetimeValue() must be of the type string, null returned.",
+            "The BCP export failed",
```
Comment (pivnicek) [inline tests/Keboola/DbExtractor/ApplicationTest.php]: @tomasfejfar this is the change to the test, catches any BCP failure

Comment (tomasfejfar) [reply tests/Keboola/DbExtractor/ApplicationTest.php]: oh, I see... sorry

Comment (tomasfejfar) [reply tests/Keboola/DbExtractor/ApplicationTest.php]: I got misled by the "not contains". So that test actually tested it, it failed, but the BCP error was different, so it was a success.

File: src/Keboola/DbExtractor/Extractor/MSSQL.php (hunk 1 above)
Comment (pivnicek) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: yes, I'm fixing this now

File: tests/Keboola/DbExtractor/ApplicationTest.php (hunk 2 above)
Comment (pivnicek) [reply tests/Keboola/DbExtractor/ApplicationTest.php]: yes, exactly

File: src/Keboola/DbExtractor/Extractor/MSSQL.php [hunk 3]
```diff
@@ -757,7 +757,7 @@ public function validateIncrementalFetching(array $table, string $columnName, ?i
             );
         }
 
-        if (in_array($columns[0]['data_type'], MssqlDataType::getNumericTypes())) {
+        if (in_array($columns[0]['data_type'], array_merge(MssqlDataType::getNumericTypes(), ['smalldatetime']))) {
```
[the remark this answers is not in the document]
Comment (pivnicek) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: yeha, I'll do this, it's a hack for sure, just wanted to confirm solution.

File: src/Keboola/DbExtractor/Extractor/MSSQL.php [hunk 4]
```diff
@@ -116,7 +116,7 @@ private function getLastFetchedDatetimeValue(array $lastExportedLine, array $tab
             if ($whereClause !== "") {
                 $whereClause .= " AND ";
             }
-            if ($column['basetype'] === "TIMESTAMP" && strtoupper($column['type']) !== 'SMALLDATETIME') {
+            if (in_array(strtoupper($column['type']), ["DATETIME", "DATETIME2"])) {
```
[the remark this answers is not in the document]
Comment (tomasfejfar) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: I see... no basetype key!

File: src/Keboola/DbExtractor/Extractor/MSSQL.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (tomasfejfar) [reply src/Keboola/DbExtractor/Extractor/MSSQL.php]: https://github.com/keboola/db-extractor-mssql/issues/104
